// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALe6ZrCbRr9Icj7ZWWzw1RY3GKeDiNjWU',
    appId: '1:18077133053:web:7008c67c58b6278b49b694',
    messagingSenderId: '18077133053',
    projectId: 'ae-coaching-bcd69',
    authDomain: 'ae-coaching-bcd69.firebaseapp.com',
    storageBucket: 'ae-coaching-bcd69.firebasestorage.app',
    measurementId: 'G-HPW6K990TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVPuWxe4bhoPfGTMeZ2NB6Ou93tKDEICY',
    appId: '1:18077133053:android:d6158ec0cef6a4a549b694',
    messagingSenderId: '18077133053',
    projectId: 'ae-coaching-bcd69',
    storageBucket: 'ae-coaching-bcd69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8RsqMlkUuLsavwJI7DWivRij5b8Jiv_c',
    appId: '1:18077133053:ios:da4eb29c85740ac549b694',
    messagingSenderId: '18077133053',
    projectId: 'ae-coaching-bcd69',
    storageBucket: 'ae-coaching-bcd69.firebasestorage.app',
    iosBundleId: 'com.example.aeCoaching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8RsqMlkUuLsavwJI7DWivRij5b8Jiv_c',
    appId: '1:18077133053:ios:da4eb29c85740ac549b694',
    messagingSenderId: '18077133053',
    projectId: 'ae-coaching-bcd69',
    storageBucket: 'ae-coaching-bcd69.firebasestorage.app',
    iosBundleId: 'com.example.aeCoaching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALe6ZrCbRr9Icj7ZWWzw1RY3GKeDiNjWU',
    appId: '1:18077133053:web:212fdcc8c575491f49b694',
    messagingSenderId: '18077133053',
    projectId: 'ae-coaching-bcd69',
    authDomain: 'ae-coaching-bcd69.firebaseapp.com',
    storageBucket: 'ae-coaching-bcd69.firebasestorage.app',
    measurementId: 'G-CZV5GSQLL8',
  );
}
